-- ════════════════════════════════════════════════════════════════════════════
-- IAM Larsil — FATIA 3: Papéis, Permissões, Escopo e Treinamento
-- ════════════════════════════════════════════════════════════════════════════
-- Generaliza o modelo do Painel PCP (PAINEL_PERFIS + escopo) para todos os sistemas.
-- Motor de escopo por TIPO + ÂNCORA (GLOBAL/COORDENADOR/SUPERVISOR/EQUIPE/PROJETO).
-- Não altera nada existente. Idempotente.
-- ════════════════════════════════════════════════════════════════════════════

-- ── Catálogo de sistemas (apps) ─────────────────────────────────────────────
IF OBJECT_ID('iam.IAM_SISTEMAS','U') IS NULL
BEGIN
    CREATE TABLE iam.IAM_SISTEMAS (
        CODIGO             VARCHAR(30)   NOT NULL CONSTRAINT PK_IAM_SISTEMAS PRIMARY KEY,
        NOME               NVARCHAR(120) NOT NULL,
        URL_BASE           NVARCHAR(255) NULL,
        EXIGE_TREINAMENTO  BIT           NOT NULL CONSTRAINT DF_IAM_SIST_TREINO DEFAULT (0),
        ATIVO              BIT           NOT NULL CONSTRAINT DF_IAM_SIST_ATIVO DEFAULT (1),
        CRIADO_EM          DATETIME2(0)  NOT NULL CONSTRAINT DF_IAM_SIST_CRIADO DEFAULT (SYSUTCDATETIME())
    );
END
GO

-- ── Permissões granulares (sistema.modulo.acao) ─────────────────────────────
IF OBJECT_ID('iam.IAM_PERMISSOES','U') IS NULL
BEGIN
    CREATE TABLE iam.IAM_PERMISSOES (
        CODIGO          VARCHAR(80)   NOT NULL CONSTRAINT PK_IAM_PERMISSOES PRIMARY KEY,
        SISTEMA_CODIGO  VARCHAR(30)   NOT NULL,
        DESCRICAO       NVARCHAR(200) NULL,
        CONSTRAINT FK_IAM_PERM_SIST FOREIGN KEY (SISTEMA_CODIGO) REFERENCES iam.IAM_SISTEMAS(CODIGO)
    );
    CREATE INDEX IX_IAM_PERM_SIST ON iam.IAM_PERMISSOES (SISTEMA_CODIGO);
END
GO

-- ── Papéis (cargos-molde) ───────────────────────────────────────────────────
IF OBJECT_ID('iam.IAM_PAPEIS','U') IS NULL
BEGIN
    CREATE TABLE iam.IAM_PAPEIS (
        ID                  INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_IAM_PAPEIS PRIMARY KEY,
        NOME                VARCHAR(40)   NOT NULL CONSTRAINT UQ_IAM_PAPEIS_NOME UNIQUE,
        -- escopo sugerido ao aplicar este papel: GLOBAL/COORDENADOR/SUPERVISOR/EQUIPE/PROJETO/NENHUM
        ESCOPO_TIPO_PADRAO  VARCHAR(20)   NOT NULL CONSTRAINT DF_IAM_PAPEIS_ESC DEFAULT ('NENHUM'),
        DESCRICAO           NVARCHAR(200) NULL
    );
END
GO

-- ── Quais permissões cada papel concede por padrão ──────────────────────────
IF OBJECT_ID('iam.IAM_PAPEL_PERMISSOES','U') IS NULL
BEGIN
    CREATE TABLE iam.IAM_PAPEL_PERMISSOES (
        PAPEL_ID          INT         NOT NULL,
        PERMISSAO_CODIGO  VARCHAR(80) NOT NULL,
        CONSTRAINT PK_IAM_PAPEL_PERM PRIMARY KEY (PAPEL_ID, PERMISSAO_CODIGO),
        CONSTRAINT FK_IAM_PP_PAPEL FOREIGN KEY (PAPEL_ID) REFERENCES iam.IAM_PAPEIS(ID),
        CONSTRAINT FK_IAM_PP_PERM  FOREIGN KEY (PERMISSAO_CODIGO) REFERENCES iam.IAM_PERMISSOES(CODIGO)
    );
END
GO

-- ── Papéis de cada usuário ──────────────────────────────────────────────────
IF OBJECT_ID('iam.IAM_USUARIO_PAPEIS','U') IS NULL
BEGIN
    CREATE TABLE iam.IAM_USUARIO_PAPEIS (
        USUARIO_ID  INT          NOT NULL,
        PAPEL_ID    INT          NOT NULL,
        CRIADO_EM   DATETIME2(0) NOT NULL CONSTRAINT DF_IAM_UP_CRIADO DEFAULT (SYSUTCDATETIME()),
        CRIADO_POR  NVARCHAR(120) NULL,
        CONSTRAINT PK_IAM_USUARIO_PAPEIS PRIMARY KEY (USUARIO_ID, PAPEL_ID),
        CONSTRAINT FK_IAM_UP_USER  FOREIGN KEY (USUARIO_ID) REFERENCES iam.IAM_USUARIOS(ID),
        CONSTRAINT FK_IAM_UP_PAPEL FOREIGN KEY (PAPEL_ID)   REFERENCES iam.IAM_PAPEIS(ID)
    );
END
GO

-- ── Escopo de cada usuário (tipo + âncora) — pode ter várias linhas ─────────
IF OBJECT_ID('iam.IAM_USUARIO_ESCOPO','U') IS NULL
BEGIN
    CREATE TABLE iam.IAM_USUARIO_ESCOPO (
        ID          INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_IAM_USUARIO_ESCOPO PRIMARY KEY,
        USUARIO_ID  INT          NOT NULL,
        TIPO        VARCHAR(20)  NOT NULL,   -- GLOBAL/COORDENADOR/SUPERVISOR/EQUIPE/PROJETO
        VALOR       NVARCHAR(255) NULL,       -- nome (coord/sup) ou código (equipe/projeto); NULL p/ GLOBAL
        CRIADO_EM   DATETIME2(0) NOT NULL CONSTRAINT DF_IAM_UE_CRIADO DEFAULT (SYSUTCDATETIME()),
        CRIADO_POR  NVARCHAR(120) NULL,
        CONSTRAINT FK_IAM_UE_USER FOREIGN KEY (USUARIO_ID) REFERENCES iam.IAM_USUARIOS(ID)
    );
    CREATE UNIQUE INDEX UX_IAM_UE ON iam.IAM_USUARIO_ESCOPO (USUARIO_ID, TIPO, VALOR)
        WHERE VALOR IS NOT NULL;
    CREATE INDEX IX_IAM_UE_USER ON iam.IAM_USUARIO_ESCOPO (USUARIO_ID);
END
GO

-- ── Exceções por usuário (conceder/negar permissão pontual) ─────────────────
IF OBJECT_ID('iam.IAM_USUARIO_PERMISSOES','U') IS NULL
BEGIN
    CREATE TABLE iam.IAM_USUARIO_PERMISSOES (
        USUARIO_ID        INT          NOT NULL,
        PERMISSAO_CODIGO  VARCHAR(80)  NOT NULL,
        TIPO              VARCHAR(10)  NOT NULL,  -- CONCEDER | NEGAR
        CRIADO_EM         DATETIME2(0) NOT NULL CONSTRAINT DF_IAM_UPERM_CRIADO DEFAULT (SYSUTCDATETIME()),
        CRIADO_POR        NVARCHAR(120) NULL,
        CONSTRAINT PK_IAM_USUARIO_PERM PRIMARY KEY (USUARIO_ID, PERMISSAO_CODIGO),
        CONSTRAINT FK_IAM_UPERM_USER FOREIGN KEY (USUARIO_ID) REFERENCES iam.IAM_USUARIOS(ID),
        CONSTRAINT FK_IAM_UPERM_PERM FOREIGN KEY (PERMISSAO_CODIGO) REFERENCES iam.IAM_PERMISSOES(CODIGO)
    );
END
GO

-- ── Treinamento por usuário + sistema ───────────────────────────────────────
IF OBJECT_ID('iam.IAM_USUARIO_TREINAMENTOS','U') IS NULL
BEGIN
    CREATE TABLE iam.IAM_USUARIO_TREINAMENTOS (
        USUARIO_ID        INT          NOT NULL,
        SISTEMA_CODIGO    VARCHAR(30)  NOT NULL,
        TREINADO          BIT          NOT NULL CONSTRAINT DF_IAM_TREINO DEFAULT (0),
        DATA_TREINAMENTO  DATE         NULL,
        TREINADO_POR      NVARCHAR(120) NULL,
        ATUALIZADO_EM     DATETIME2(0) NULL,
        CONSTRAINT PK_IAM_USUARIO_TREINO PRIMARY KEY (USUARIO_ID, SISTEMA_CODIGO),
        CONSTRAINT FK_IAM_TREINO_USER FOREIGN KEY (USUARIO_ID) REFERENCES iam.IAM_USUARIOS(ID),
        CONSTRAINT FK_IAM_TREINO_SIST FOREIGN KEY (SISTEMA_CODIGO) REFERENCES iam.IAM_SISTEMAS(CODIGO)
    );
END
GO
